from __future__ import annotations

import importlib
import sys
from types import ModuleType, SimpleNamespace


def _install_stubs(decision: str, suggestion: str | None = None) -> None:
    langgraph_types = ModuleType("langgraph.types")
    graph_message_mod = ModuleType("langgraph.graph.message")
    graph_message_mod.add_messages = lambda current, new: (current or []) + (new or [])

    def _interrupt(_payload):
        data = {"action": decision}
        if suggestion is not None:
            data["suggestion"] = suggestion
        return data

    langgraph_types.interrupt = _interrupt

    messages_mod = ModuleType("langchain_core.messages")

    class _HumanMessage:
        def __init__(self, content: str):
            self.type = "human"
            self.content = content

    class _AIMessage:
        def __init__(self, content: str, additional_kwargs: dict | None = None):
            self.type = "ai"
            self.content = content
            self.additional_kwargs = additional_kwargs or {}

    messages_mod.HumanMessage = _HumanMessage
    messages_mod.AIMessage = _AIMessage
    messages_mod.BaseMessage = SimpleNamespace

    sys.modules["langgraph.types"] = langgraph_types
    sys.modules["langgraph.graph.message"] = graph_message_mod
    sys.modules["langchain_core.messages"] = messages_mod


def test_human_review_before_output_only_emits_result_message_on_approve() -> None:
    _install_stubs(decision="approve")
    sys.modules.pop("graph.nodes.human_review_before_output", None)
    mod = importlib.import_module("graph.nodes.human_review_before_output")

    state = {
        "messages": [],
        "output": {
            "generated_code": "print(1)",
            "code_summary": "Prints one.",
            "code_assumptions": "No assumptions.",
            "text": "ok",
            "figure_artifact_id": "fig-1",
        },
        "artifacts": {
            "conversation_events": [],
            "conversation_events_version": 1,
            "artifact_manifest_version": 1,
            "files": {
                "fig-1": {
                    "artifact_id": "fig-1",
                    "kind": "figure",
                    "producer": "executor",
                    "mime": "image/png",
                    "summary": "Figure generated by approved Python code.",
                    "created_at": "2026-04-30T00:00:00Z",
                    "content": {"path": "/tmp/figure.png"},
                }
            },
        },
        "agents": {},
    }

    updated = mod.human_review_before_output_node(state)
    assert len(updated["messages"]) == 1
    assert updated["messages"][0].type == "ai"
    assert "Prints one." in updated["messages"][0].content
    assert "No assumptions." in updated["messages"][0].content
    assert updated["messages"][0].additional_kwargs["figure_path"] == "/tmp/figure.png"
    events = updated["artifacts"]["conversation_events"]
    assert events[-2]["type"] == "assistant"
    assert events[-2]["actor"] == "human_review_before_output"
    assert "Generated code:" in events[-2]["text"]
    assert events[-1]["type"] == "figure"
    assert events[-1]["actor"] == "human_review_before_output"
    assert events[-1]["artifact_id"] == "fig-1"
    assert events[-1]["parent_event_id"] == events[-2]["event_id"]
    assert updated["agents"]["human_review"]["final_decision"] == "approve"


def test_human_review_before_output_regenerate_skips_result_message_and_keeps_suggestion() -> None:
    _install_stubs(decision="regenerate", suggestion="add covariates")
    sys.modules.pop("graph.nodes.human_review_before_output", None)
    mod = importlib.import_module("graph.nodes.human_review_before_output")

    state = {
        "messages": [],
        "output": {"generated_code": "print(1)", "text": "ok"},
        "agents": {},
    }

    updated = mod.human_review_before_output_node(state)
    assert len(updated["messages"]) == 1
    assert updated["messages"][0].type == "human"
    assert updated["messages"][0].content == "add covariates"
    assert updated["agents"]["human_review"]["final_decision"] == "regenerate"
